apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vault-deployment
  namespace: vault
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: vault
    spec:
      volumes:
        - name: config-volume
          secret:
            secretName: vault-secrets
            defaultMode: 0777
      containers:
        - name: vault
          args:
            - server
          image: vault:0.6.4
          env:
            - name: VAULT_REDIRECT_ADDR
              value: http://vault:8200
            - name: VAULT_CLUSTER_ADDR
              value: http://vault:8201
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
          ports:
            - containerPort: 8200
              name: vault
            - containerPort: 8201
              name: cluster-addr
          volumeMounts:
            - name: config-volume
              mountPath: /vault/config
          securityContext:
             capabilities:
               add:
                 - IPC_LOCK