apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    name: vault
spec:
  clusterIP: None
  ports:
    - name: vault
      port: 8200
    - name: cluster-addr
      port: 8201
  selector:
    app: vault
